import type { Metadata } from "next";
import "./globals.css";
// import Header from "@/components/Header";
// import Navbar from "@/components/NavBar";
// import ThemeChanger from "@/components/ThemeChanger";

export const metadata: Metadata = {
  title: "Food Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* <Header /> */}
        {/* <Navbar /> */}

        <div id="popup-root"></div>
        {children}
      </body>
    </html>
  );
}
